config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  # Admin routes
  namespace :admin do
    resources :schools, only: [:index, :new, :create] do
      resources :school_admins, only: [:new, :create]
    end
  end

  # SchoolAdmin routes
  namespace :school_admin do
    resources :schools, only: [:edit, :update] do
      resources :courses, only: [:index, :new, :create]
      resources :batches, only: [:index, :new, :create, :show, :update] do
        resources :enrolment_requests, only: [:index, :update]
      end
    end
  end

end

app/models/batch.rb
class Batch < ApplicationRecord
  belongs_to :course
  has_many :enrolment_requests, dependent: :destroy
  has_many :students, dependent: :nullify
  has_many :school_admin_batches, dependent: :destroy
  has_many :school_admins, through: :school_admin_batches

  validates :name, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :start_date_cannot_be_in_the_past
  validate :end_date_cannot_be_before_start_date

  private

  def start_date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
  end

  def end_date_cannot_be_before_start_date
    if end_date.present? && end_date < start_date
      errors.add(:end_date, "can't be before start date")
    end
  end

end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_action :set_batch, only: %i[ show edit update destroy ]

  # GET /batches or /batches.json
  def index
    @batches = Batch.all
  end

  # GET /batches/1 or /batches/1.json
  def show
  end

  # GET /batches/new
  def new
    @batch = Batch.new
  end

  # GET /batches/1/edit
  def edit
  end

  # POST /batches or /batches.json
  def create
    @batch = Batch.new(batch_params)

    respond_to do |format|
      if @batch.save
        format.html { redirect_to batch_url(@batch), notice: "Batch was successfully created." }
        format.json { render :show, status: :created, location: @batch }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /batches/1 or /batches/1.json
  def update
    respond_to do |format|
      if @batch.update(batch_params)
        format.html { redirect_to batch_url(@batch), notice: "Batch was successfully updated." }
        format.json { render :show, status: :ok, location: @batch }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @batch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batches/1 or /batches/1.json
  def destroy
    @batch.destroy

    respond_to do |format|
      format.html { redirect_to batches_url, notice: "Batch was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_batch
      @batch = Batch.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def batch_params
      params.require(:batch).permit(:name, :start_date, :end_date, :course_id)
    end
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/views/batches/_form.html.erb
<%= form_with(model: batch, local: true) do |form| %>
  <% if batch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(batch.errors.count, "error") %> prohibited this batch from being saved:</h2>

      <ul>
        <% batch.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.text_field :course_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/batches/edit.html.erb
<h1>Editing Batch</h1>

<%= render 'form', batch: @batch %>

<%= link_to 'Show', @batch %> |
<%= link_to 'Back', batches_path %>

app/views/batches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Batches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @batches.each do |batch| %>
      <tr>
        <td><%= batch.name %></td>
        <td><%= batch.start_date %></td>
        <td><%= batch.end_date %></td>
        <td><%= batch.course_id %></td>
        <td><%= link_to 'Show', batch %></td>
        <td><%= link_to 'Edit', edit_batch_path(batch) %></td>
        <td><%= link_to 'Destroy', batch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Batch', new_batch_path %>

app/views/batches/new.html.erb
<h1>New Batch</h1>

<%= render 'form', batch: @batch %>

<%= link_to 'Back', batches_path %>

app/views/batches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @batch.name %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @batch.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @batch.end_date %>
</p>

<p>
  <strong>Course:</strong>
  <%= @batch.course_id %>
</p>

<%= link_to 'Edit', edit_batch_path(@batch) %> |
<%= link_to 'Back', batches_path %>